import { motion } from "framer-motion";
import Head from "next/head";
import styles from "./../styles/Home.module.scss";
import Post from "../components/Post/Post";
import AddPostForm from "../components/AddPostForm/AddPostForm";
export default function Home() {
  return (
    <div className={styles["home"]}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles["container"]}>
        <main className={styles.main}>
          <h1 className={styles.title}>My Post</h1>
        </main>
        <ul className={styles["tweets-list"]}>
          <Post
            content={'This is my tweet it is very cool and I"m making cool app'}
            date={"02/07/2077"}
          />
          <Post
            content={'This is my tweet it is very cool and I"m making cool app'}
            date={"02/07/2077"}
          />
          <Post
            content={'This is my tweet it is very cool and I"m making cool app'}
            date={"02/07/2077"}
          />
        </ul>
        <AddPostForm />
      </div>
    </div>
  );
}
