import { motion } from "framer-motion";
import Head from "next/head";
import styles from "./../../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles["home"]}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles["container"]}>
        <main className={styles.main}>
          <h1 className={styles.title}>My Post</h1>
        </main>
        <ul className={styles["tweets-list"]}>
          <li>
            <p className={styles["content"]}>
              I'm working in figma trying to design a new website that load my
              tweets
            </p>
            <p className={styles["date"]}>2/27/2077</p>
          </li>

          <li>
            <p className={styles["content"]}>
              I'm working in figma trying to design a new website that load my
              tweets
            </p>
            <p className={styles["date"]}>2/27/2077</p>
          </li>

          <li>
            <p className={styles["content"]}>
              I'm working in figma trying to design a new website that load my
              tweets
            </p>
            <p className={styles["date"]}>2/27/2077</p>
          </li>
        </ul>

        <form className={styles["add-post-form"]}>
          <textarea></textarea>
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            transition={{ duration: 0.2 }}
          >
            Add New Post
          </motion.button>
        </form>
      </div>
    </div>
  );
}
